name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Checks out repository under $GITHUB_WORKSPACE, so workflow can access it
      - name: Checkout
        uses: actions/checkout@v3

      #Setup node in order for both frontend and backend to properly start up
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 15

      #Setup local mongodb server instead of using cluster
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      #Run server in background by ending command w/a "&"
      - name: Start server
        working-directory: ./backend
        run: npm run dev &
        env:
          PORT: 4000
          #Use the local mongodb server in the runner rather than cloud
          DB: mongodb://localhost:27017

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./frontend
          build: npm run build
          start: npm run dev
          browser: firefox
        env:
          VITE_BACKEND_URL: http://localhost:4000
