name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Checks out repository under $GITHUB_WORKSPACE, so workflow can access it
      - name: Checkout
        uses: actions/checkout@v3

      #Setup node in order for both frontend and backend to properly start up
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      #Run server in background by ending command w/a "&"
      - name: Start server
        working-directory: ./backend
        run: node index.js &
        env:
          PORT: 4000
          DB: ${{ secrets.DB }}

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./frontend
          build: npm run build
          start: npm run dev
        env:
          VITE_BACKEND_URL: http://localhost:4000
